name=input("Enter your name ")
branch=input("Enter your branch ")
gen=input("Enter your gender ")
coll=input("Enter your college name ")
age=int(input("Enter age of student "))
print("Name:",name)
print("Branch:",branch)
print("Gender:",gen)
print("College name:",coll)
print("Age:",age)
